// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const listarAlunos = `-- name: ListarAlunos :many
SELECT id, nome, foto, turma, criado_em
FROM alunos
ORDER BY id
`

func (q *Queries) ListarAlunos(ctx context.Context) ([]Aluno, error) {
	rows, err := q.db.QueryContext(ctx, listarAlunos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Aluno
	for rows.Next() {
		var i Aluno
		if err := rows.Scan(&i.ID, &i.Nome, &i.Foto, &i.Turma, &i.CriadoEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarAlunoPorID = `-- name: BuscarAlunoPorID :one
SELECT id, nome, foto, turma, criado_em
FROM alunos
WHERE id = $1
`

func (q *Queries) BuscarAlunoPorID(ctx context.Context, id int32) (Aluno, error) {
	row := q.db.QueryRowContext(ctx, buscarAlunoPorID, id)
	var i Aluno
	err := row.Scan(&i.ID, &i.Nome, &i.Foto, &i.Turma, &i.CriadoEm)
	return i, err
}

const criarAluno = `-- name: CriarAluno :one
INSERT INTO alunos (nome, foto, turma)
VALUES ($1, $2, $3)
RETURNING id, nome, foto, turma, criado_em
`

type CriarAlunoParams struct {
	Nome  string
	Foto  sql.NullString
	Turma sql.NullString
}

func (q *Queries) CriarAluno(ctx context.Context, arg CriarAlunoParams) (Aluno, error) {
	row := q.db.QueryRowContext(ctx, criarAluno, arg.Nome, arg.Foto, arg.Turma)
	var i Aluno
	err := row.Scan(&i.ID, &i.Nome, &i.Foto, &i.Turma, &i.CriadoEm)
	return i, err
}

const atualizarAluno = `-- name: AtualizarAluno :one
UPDATE alunos
SET nome = $2, foto = $3, turma = $4
WHERE id = $1
RETURNING id, nome, foto, turma, criado_em
`

type AtualizarAlunoParams struct {
	ID    int32
	Nome  string
	Foto  sql.NullString
	Turma sql.NullString
}

func (q *Queries) AtualizarAluno(ctx context.Context, arg AtualizarAlunoParams) (Aluno, error) {
	row := q.db.QueryRowContext(ctx, atualizarAluno, arg.ID, arg.Nome, arg.Foto, arg.Turma)
	var i Aluno
	err := row.Scan(&i.ID, &i.Nome, &i.Foto, &i.Turma, &i.CriadoEm)
	return i, err
}

const removerAluno = `-- name: RemoverAluno :one
DELETE FROM alunos
WHERE id = $1
RETURNING id
`

func (q *Queries) RemoverAluno(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, removerAluno, id)
	var deletedID int32
	err := row.Scan(&deletedID)
	return deletedID, err
}

const contarAlunos = `-- name: ContarAlunos :one
SELECT COUNT(*) FROM alunos
`

func (q *Queries) ContarAlunos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, contarAlunos)
	var count int64
	err := row.Scan(&count)
	return count, err
}
