// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x
// source: query.sql

package db

import (
	"context"
	"time"
)

const buscarAdminPorUsuario = `-- name: BuscarAdminPorUsuario :one
SELECT id, usuario, senha_hash, role, criado_em
FROM admins
WHERE usuario = $1
`

func (q *Queries) BuscarAdminPorUsuario(ctx context.Context, usuario string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, buscarAdminPorUsuario, usuario)
	var i Admin
	err := row.Scan(&i.ID, &i.Usuario, &i.SenhaHash, &i.Role, &i.CriadoEm)
	return i, err
}

const buscarAdminPorID = `-- name: BuscarAdminPorID :one
SELECT id, usuario, senha_hash, role, criado_em
FROM admins
WHERE id = $1
`

func (q *Queries) BuscarAdminPorID(ctx context.Context, id int32) (Admin, error) {
	row := q.db.QueryRowContext(ctx, buscarAdminPorID, id)
	var i Admin
	err := row.Scan(&i.ID, &i.Usuario, &i.SenhaHash, &i.Role, &i.CriadoEm)
	return i, err
}

const criarAdmin = `-- name: CriarAdmin :one
INSERT INTO admins (usuario, senha_hash, role)
VALUES ($1, $2, $3)
RETURNING id, usuario, senha_hash, role, criado_em
`

type CriarAdminParams struct {
	Usuario   string
	SenhaHash string
	Role      string
}

func (q *Queries) CriarAdmin(ctx context.Context, arg CriarAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, criarAdmin, arg.Usuario, arg.SenhaHash, arg.Role)
	var i Admin
	err := row.Scan(&i.ID, &i.Usuario, &i.SenhaHash, &i.Role, &i.CriadoEm)
	return i, err
}

const criarRefreshToken = `-- name: CriarRefreshToken :exec
INSERT INTO refresh_tokens (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CriarRefreshTokenParams struct {
	AdminID   int32
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CriarRefreshToken(ctx context.Context, arg CriarRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, criarRefreshToken, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const buscarRefreshTokenAtivo = `-- name: BuscarRefreshTokenAtivo :one
SELECT id, admin_id, token_hash, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) BuscarRefreshTokenAtivo(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, buscarRefreshTokenAtivo, tokenHash)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.AdminID, &i.TokenHash, &i.ExpiresAt, &i.RevokedAt, &i.CreatedAt)
	return i, err
}

const revogarRefreshToken = `-- name: RevogarRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevogarRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revogarRefreshToken, tokenHash)
	return err
}
