// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listarEventos = `-- name: ListarEventos :many
SELECT id, titulo, descricao, data, imagem_url, criado_em
FROM eventos
ORDER BY data
`

func (q *Queries) ListarEventos(ctx context.Context) ([]Evento, error) {
	rows, err := q.db.QueryContext(ctx, listarEventos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Evento
	for rows.Next() {
		var i Evento
		if err := rows.Scan(&i.ID, &i.Titulo, &i.Descricao, &i.Data, &i.ImagemUrl, &i.CriadoEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarEventoPorID = `-- name: BuscarEventoPorID :one
SELECT id, titulo, descricao, data, imagem_url, criado_em
FROM eventos
WHERE id = $1
`

func (q *Queries) BuscarEventoPorID(ctx context.Context, id int32) (Evento, error) {
	row := q.db.QueryRowContext(ctx, buscarEventoPorID, id)
	var i Evento
	err := row.Scan(&i.ID, &i.Titulo, &i.Descricao, &i.Data, &i.ImagemUrl, &i.CriadoEm)
	return i, err
}

const criarEvento = `-- name: CriarEvento :one
INSERT INTO eventos (titulo, descricao, data, imagem_url)
VALUES ($1, $2, $3, $4)
RETURNING id, titulo, descricao, data, imagem_url, criado_em
`

type CriarEventoParams struct {
	Titulo    string
	Descricao string
	Data      time.Time
	ImagemUrl sql.NullString
}

func (q *Queries) CriarEvento(ctx context.Context, arg CriarEventoParams) (Evento, error) {
	row := q.db.QueryRowContext(ctx, criarEvento, arg.Titulo, arg.Descricao, arg.Data, arg.ImagemUrl)
	var i Evento
	err := row.Scan(&i.ID, &i.Titulo, &i.Descricao, &i.Data, &i.ImagemUrl, &i.CriadoEm)
	return i, err
}

const atualizarEvento = `-- name: AtualizarEvento :one
UPDATE eventos
SET titulo = $2, descricao = $3, data = $4, imagem_url = $5
WHERE id = $1
RETURNING id, titulo, descricao, data, imagem_url, criado_em
`

type AtualizarEventoParams struct {
	ID        int32
	Titulo    string
	Descricao string
	Data      time.Time
	ImagemUrl sql.NullString
}

func (q *Queries) AtualizarEvento(ctx context.Context, arg AtualizarEventoParams) (Evento, error) {
	row := q.db.QueryRowContext(ctx, atualizarEvento, arg.ID, arg.Titulo, arg.Descricao, arg.Data, arg.ImagemUrl)
	var i Evento
	err := row.Scan(&i.ID, &i.Titulo, &i.Descricao, &i.Data, &i.ImagemUrl, &i.CriadoEm)
	return i, err
}

const removerEvento = `-- name: RemoverEvento :one
DELETE FROM eventos
WHERE id = $1
RETURNING id
`

func (q *Queries) RemoverEvento(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, removerEvento, id)
	var deletedID int32
	err := row.Scan(&deletedID)
	return deletedID, err
}
