// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const listarFotosPorAluno = `-- name: ListarFotosPorAluno :many
SELECT id, aluno_id, url, legenda, enviado_em
FROM fotos
WHERE aluno_id = $1
ORDER BY id
`

func (q *Queries) ListarFotosPorAluno(ctx context.Context, alunoID int32) ([]Foto, error) {
	rows, err := q.db.QueryContext(ctx, listarFotosPorAluno, alunoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Foto
	for rows.Next() {
		var i Foto
		if err := rows.Scan(&i.ID, &i.AlunoID, &i.Url, &i.Legenda, &i.EnviadoEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criarFoto = `-- name: CriarFoto :one
INSERT INTO fotos (aluno_id, url, legenda)
VALUES ($1, $2, $3)
RETURNING id, aluno_id, url, legenda, enviado_em
`

type CriarFotoParams struct {
	AlunoID int32
	Url     string
	Legenda sql.NullString
}

func (q *Queries) CriarFoto(ctx context.Context, arg CriarFotoParams) (Foto, error) {
	row := q.db.QueryRowContext(ctx, criarFoto, arg.AlunoID, arg.Url, arg.Legenda)
	var i Foto
	err := row.Scan(&i.ID, &i.AlunoID, &i.Url, &i.Legenda, &i.EnviadoEm)
	return i, err
}
