// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID        int32
	Usuario   string
	SenhaHash string
	Role      string
	CriadoEm  time.Time
}

type Aluno struct {
	ID       int32
	Nome     string
	Foto     sql.NullString
	Turma    sql.NullString
	CriadoEm time.Time
}

type Evento struct {
	ID        int32
	Titulo    string
	Descricao string
	Data      time.Time
	ImagemUrl sql.NullString
	CriadoEm  time.Time
}

type Foto struct {
	ID        int32
	AlunoID   int32
	Url       string
	Legenda   sql.NullString
	EnviadoEm time.Time
}

type RefreshToken struct {
	ID        int32
	AdminID   int32
	TokenHash string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}
